# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Define jobs to be invoked later in a workflow.
jobs:
  build-and-test:
    # Specify the execution environment.
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout

      - python/install-packages:
          args: unittest
          pkg-manager: pipenv

      - python/test:
          test-tool: unittest
          pkg-manager: pipenv
          ensure-test-tool: true 
          fail-if-missing-tool: false
          pypi-cache: true
          venv-cache: true
          test-tool-args: discover -s tests  

# Invoke jobs via workflows
workflows:
  built-and-test-workflow:
    jobs:
      - build-and-test
