# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Define jobs to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment.
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - python/install-packages
      
      - run:
          name: "Run Unittest with Coverage"
          command: coverage run -m unittest discover tests

# Invoke jobs via workflows
workflows:
    built-and-test-workflow:
      jobs:
        - build
