# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Define jobs to be invoked later in a workflow.
jobs:
  build-and-test:
    # Specify the execution environment.
    executor: python/default

    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip

# Invoke jobs via workflows
workflows:
  built-and-test-workflow:
    jobs:
      - build-and-test
