# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.0.3
  browser-tools: circleci/browser-tools@1.3.0

# Define jobs to be invoked later in a workflow.
jobs:
  build:
    # Specify the execution environment.
    docker:
      - image: cimg/python:3.10

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - python/install-packages
      
      - run:
          name: "Run Unittest with Coverage"
          command: |
            coverage run -m unittest discover tests
            coverage report
            coverage html

      - store_artifacts:
          path: htmlcov

# Invoke jobs via workflows
workflows:
    built-and-test-workflow:
      jobs:
        - build
