# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.0.3

# Define jobs to be invoked later in a workflow.
jobs:
  build-and-test:
    # Specify the execution environment.
    executor: python

    # Add steps to the job
    steps:
      - checkout
      - python/test:
          version: '3.10.5' 
          test-tool: unittest 

# Invoke jobs via workflows
workflows:
  built-and-test-workflow:
    jobs:
      - build-and-test
